<?php include "header.php"; ?>
<body data-spy="scroll" data-target="#navbar" data-offset="70" style="overflow: visible; justify-content: center;">

	<!-- Preloader -->
	<div id="preloader" style="display: none;">
		<div id="status" style="display: none;">&nbsp;</div>
	</div>
	<!--  -->

	<!-- header -->
	<header>
		<!-- navbar -->
		<nav id="navbar" class="navbar navbar-custom navbar-fixed-top affix-top" data-spy="affix" data-offset-top="70">
			<div class="container">
				<div class="row">
					<!-- Brand and toggle get grouped for better mobile display -->
					<div class="navbar-header page-scroll">
						<button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
							<i class="fa fa-bars"></i>
						</button>
						<a class="navbar-brand page-scroll logo-light" style="width: 135px;height: 45px;" href="/"><img alt="" src="img/svgs/MainJyroLogo.svg"></a>
						<a class="navbar-brand page-scroll logo-clr" style="width: 135px;height: 45px;" href="/"><img alt="" src="img/svgs/MainJyroLogo.svg"></a>
					</div>

					<!-- Collect the nav links, forms, and other content for toggling -->
					<div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
						<div class="right-nav text-right">
							<!-- <ul class="nav navbar-nav menu">
								<li class="active">
									<a href="#home">Home</a>
								</li>
								<li>
									<a href="#feature">Feature</a>
								</li>
								<li>
									<a href="#overview">Overview</a>
								</li>
								<li>
									<a href="#How">How Work?</a>
								</li>
								<li>
									<a href="#team">Team</a>
								</li>
							</ul> -->
						</div>
					</div>
					<!-- /.navbar-collapse -->
				</div>
			</div>
		</nav>
		<!-- End navbar -->

		<!-- banner -->
<div id="privacy" style="padding-top: 150px;">
    <div class="container">
    <h4>Privacy Policy</h4>
    <p>
    Updated at 2020-08-28
    </p>
    <br>

    <p>
      Jyro (“we,” “our,” or “us”) is committed to protecting your privacy. This Privacy Policy explains how your personal information is collected, used, and disclosed by Jyro.  </p>
    <br>

    <p>
      This Privacy Policy applies to our website, and its associated subdomains (collectively, our “Service”) alongside our application, Jyro. By accessing or using our Service, you signify that you have read, understood, and agree to our collection, storage, use, and disclosure of your personal information as described in this Privacy Policy and our Terms of Service.
    </p>
    <br>
  
    <h4>Meanings</h4>
    <p>
    For this Privacy Policy:
    </p>
    <br>
   
    <p>
      1. You is referred to the person who accessed the Service, or the company, or other legal entity on behalf of which such
      individual is accessing or using the Service, as applicable.<br>
      2. Company (referred to as either "the Company", "We", "Us" or "Our" in this Agreement) refers to Front-TSL Limited, Lagos<br>
      3. Website is referred to Jyro.<br>
      4. Service is referred to the website/app.<br>
      5. Service Provider means any natural or legal person who processes the data on behalf of the Company. It refers to
      third-party companies or individuals employed by the Company to facilitate the Service, to provide the Service on behalf of the Company, to perform services related to the Service or to assist the Company in analyzing how the Service is used.<br>
      6. Third-party Social Media Service could be any website or social network website in which a User can log in or create an
      account to use the Service.<br>
      7. Personal Data is any information that relates to an identified or identifiable individual.<br>
      8. Cookies are a small amount of data generated by a website and saved by your web browser. Its purpose is to remember information about you, similar to a preference file created by a software application.<br>
      9. Device could be any device with internet who can access the service such as a mobile phone, a computer or a digital tablet.<br>
      10. Usage Data it’s referred to the data that’s been collected automatically, either generated by the use of the Service or from the Service infrastructure itself. For example, how many times the user accessed the website/app.<br>
      
    
    </p>
    <br>
  





    <h4>What Information Do We Collect?</h4>
    <p>
      We collect information from you when you visit our website/app, register on our site, place an order, subscribe to our newsletter, respond to a survey or fill out a form.
    </p>
    <br>

    <p>
      1. Email address<br>
      2. Name / username<br>
      3. Physical address<br>
      4. Age<br>
      5. Social media profile information<br>
    </p>
    <br>

    <p>We also collect information from mobile devices for a better user experience, although these features are completely optional:</p><p>

    <br>
    </p><p>
      1. Location (GPS): Location data helps to create an accurate representation of your interests, and this can be used to bring more targeted and relevant ads to potential customers.<br>
      2. Phonebook (Contacts list): Your contacts list allows the website/app to be much more easy to use by the user, since accessing your contacts from the app makes you save tons of time.<br>
      3. Camera (Pictures): Granting camera permission allows the user to upload any picture straight from the website/app, you can safely deny camera permissions for this website/app.<br>
    </p>
    <br>
  


    <h4>How Do We Use The Information We Collect?</h4>
    <p>
      Any of the information we collect from you may be used in one of the following ways:
    </p>
    <br>

    <p>
      1. To personalize your experience (your information helps us to better respond to your individual needs<br>
      2. To improve our website/app (we continually strive to improve our website/app offerings based on the information and feedback we receive from you)<br>
      3. To improve customer service (your information helps us to more effectively respond to your customer service requests and support needs)<br>
      4. To process transactions<br>
      5. To administer a contest, promotion, survey or other site feature<br>
      6. To send periodic emails<br>
    </p>
    <br>



    <h4>How Do We Use Your Email Address?</h4>
    <p>
      By submitting your email address on this website/app, you agree to receive emails from us. You can cancel your participation in any of these email lists at any time by clicking on the opt-out link or other unsubscribe option that is included in the respective email. We only send emails to people who have authorized us to contact them, either directly, or through a third party. We do not send unsolicited commercial emails, because we hate spam as much as you do. By submitting your email address, you also agree to allow us to use your email address for customer audience targeting on sites like Facebook, where we display custom advertising to specific people who have opted-in to receive communications from us. Email addresses submitted only through the order processing page will be used for the sole purpose of sending you information and updates pertaining to your order. If, however, you have provided the same email to us through another method, we may use it for any of the purposes stated in this Policy. Note: If at any time you would like to unsubscribe from receiving future emails, we include detailed unsubscribe instructions at the bottom of each email.
    </p>
    <br>


    <h4>How Long Do We Keep Your Information?</h4>
    <p>
      We keep your information only so long as we need it to provide Jyro to you and fulfill the purposes described in this policy. This is also the case for anyone that we share your information with and who carries out services on our behalf. When we no longer need to use your information and there is no need for us to keep it to comply with our legal or regulatory obligations, we’ll either remove it from our systems or depersonalize it so that we can't identify you.
    </p>
    <br>

    <h4>How Do We Protect Your Information?</h4>
    <p>
      We implement a variety of security measures to maintain the safety of your personal information when you place an order or enter, submit, or access your personal information. We offer the use of a secure server. All supplied sensitive/credit information is transmitted via Secure Socket Layer (SSL) technology and then encrypted into our Payment gateway providers database only to be accessible by those authorized with special access rights to such systems, and are required to keep the information confidential. After a transaction, your private information (credit cards, social security numbers, financials, etc.) is never kept on file. We cannot, however, ensure or warrant the absolute security of any information you transmit to Jyro or guarantee that your information on the Service may not be accessed, disclosed, altered, or destroyed by a breach of any of our physical, technical, or managerial safeguards.
    </p>
    <br>



    <h4>Governing Law</h4>
    <p>
    The laws of NG, excluding its conflicts of law rules, shall govern this Agreement and your use of the website/app. Your use of
    the website/app may also be subject to other local, state, national, or international laws.
    </p>
    <br>


    <h4>Your Consent</h4>
    <p>
      By using our site, registering an account, or making a purchase, you consent to this Privacy Policy.
    </p>
    <br>

    <h4>Links to Other Websites</h4>
    <p>
      Our service may contain links to other websites that are not operated by Us. If You click on a third party link, You will be directed to that third party's site. We strongly advise You to review the Privacy Policy of every site You visit.<br>
      We have no control over and assume no responsibility for the content, privacy policies or practices of any third party sites or services.<br>
    </p>
    <br>

    <h4>Cookies</h4>
    <p>
      Jyro uses "Cookies" to identify the areas of our website/app that you have visited. A Cookie is a small piece of data stored on your computer or mobile device by your web browser. We use Cookies to personalize the Content that you see on our website/app. Most web browsers can be set to disable the use of Cookies. However, if you disable Cookies, you may not be able to access functionality on our website/app correctly or at all. We never place Personally Identifiable Information in Cookies
    </p>
    <br>


    <h4>Remarketing Services</h4>
    <p>
        We use remarketing services. What Is Remarketing? In digital marketing, remarketing (or retargeting) is the practice of serving ads across the internet to people who have already visited your website. It allows your company to seem like they're “following” people around the internet by serving ads on the websites and platforms they use most.
    </p>
    <br>

    <h4>Payment Details</h4>
    <p>
      In respect to any credit card or other payment processing details you have provided us, we commit that this confidential information will be stored in the most secure manner possible.
    </p>
    <br>

    <h4>Kids' Privacy</h4>
    <p>
      We do not address anyone under the age of 13. We do not knowingly collect personally identifiable information from anyone under the age of 13. If You are a parent or guardian and You are aware that Your child has provided Us with Personal Data, please contact Us. If We become aware that We have collected Personal Data from anyone under the age of 13 without verification of parental consent, We take steps to remove that information from Our servers.
    </p>
    <br>

    <h4>Changes To Our Privacy Policy</h4>
    <p>
      If we decide to change our privacy policy, we will post those changes on this page, and/or update the Privacy Policy modification date below.
    </p>
    <br>

    <h4>Third-Party Services</h4>
    <p>
      We may display, include or make available third-party content (including data, information, applications and other products services) or provide links to third-party websites or services ("Third- Party Services").<br>
      You acknowledge and agree that Jyro shall not be responsible for any Third-Party Services, including their accuracy, completeness, timeliness, validity, copyright compliance, legality, decency, quality or any other aspect thereof. Jyro does not assume and shall not have any liability or responsibility to you or any other person or entity for any Third-Party Services.<br>
      Third-Party Services and links thereto are provided solely as a convenience to you and you access and use them entirely at your own risk and subject to such third parties' terms and conditions.<br>
    </p>
    <br>
    <p>
      Google Places<br>
      Google Places is a service that returns information about places using HTTP requests. It is operated by Google.<br>
      Google Places service may collect information from You and from Your Device for security purposes.<br>
      The information gathered by Google Places is held in accordance with the Privacy Policy of Google<br>
    </p>
    <br>

    <h4>Information Regarding Your Data Protection Rights Under General Data Protection Regulation (GDPR)</h4>
    <p>
      For the purpose of this Privacy Policy, we are a Data Controller of your personal information.<br><br>
      If you are from the European Economic Area (EEA), our legal basis for collecting and using your personal information, as described in this Privacy Policy, depends on the information we collect and the specific context in which we collect it. We may process your personal information because:<br>
    </p>
    <br>
    <p>
      1. We need to perform a contract with you, such as when you use our services<br>
      2. You have given us permission to do so<br>
      3. The processing is in our legitimate interests and it's not overridden by your rights<br>
      4. For payment processing purposes<br>
      5. To comply with the law<br>
    </p>
    <br>
    <p>
      If you are a resident of the European Economic Area (EEA), you have certain data protection rights. In certain circumstances, you have the following data protection rights:
    </p>
    <br>
    <p>
      1. The right to access, update or to delete the personal information we have on you<br>
      2. The right of rectification<br>
      3. The right to object<br>
      4. The right of restriction<br>
      5. The right to data portability<br>
      6. The right to withdraw consent<br>
    </p>
    <br>
    <p>
      Please note that we may ask you to verify your identity before responding to such requests.<br>
      You have the right to complain to a Data Protection Authority about our collection and use of your personal information.<br>
      For Powered by TCPDF (www.tcpdf.org)
      more information, please contact your local data protection authority in the European Economic Area (EEA).
    </p>
    <br>

    <h4>California Residents</h4>
    <p>
      The California Consumer Privacy Act (CCPA) requires us to disclose categories of Personal Information we collect and how we use it, the categories of sources from whom we collect Personal Information, and the third parties with whom we share it, which we have explained above.
    </p>
    <br>
    <p>
      We are also required to communicate information about rights California residents have under California law. You may exercise the following rights:
    </p>
    <br>
    
    <p>
      Right to Know and Access. You may submit a verifiable request for information regarding the: (1) categories of Personal Information we collect, use, or share; (2) purposes for which categories of Personal Information are collected or used by us; (3) categories of sources from which we collect Personal Information; and (4) specific pieces of Personal Information
      we have collected about you.<br>
      Right to Equal Service. We will not discriminate against you if you exercise your privacy rights.<br>
      Right to Delete. You may submit a verifiable request to close your account and we will delete Personal Information about
      you that we have collected.<br>
      Request that a business that sells a consumer's personal data, not sell the consumer's personal data.<br>
    </p>

    <br>
    <p>
      If you make a request, we have one month to respond to you. If you would like to exercise any of these rights, please contact us.
    </p>
    
    <br>
    
    <p>
    Your continued use of our website will be regarded as acceptance of our practices around privacy and personal information. If you have any questions about how we handle user data and personal information, feel free to contact us.<br>

    We do not sell the Personal Information of our users.<br>

    For more information about these rights, please contact us.<br>
    </p>
    <br>
    
    



    <h4>California Online Privacy Protection Act (CalOPPA)</h4>
    
    <p>
      According to CalOPPA, personal information is defined as any data that may be used to identify a person<br>
      Under the Cal PPA, California consumers have the right to:<br>
    </p>
    <br>

    <p>
      1. Request that a business that collects a consumer's personal data disclose the categories and specific pieces of personal data that a business has collected about consumers.<br>
      2. Request that a business delete any personal data about the consumer that a business has collected.<br>
      3. Request that a business that sells a consumer's personal data, not sell the consumer's personal data<br>
    </p>

    <br>

    <p>
      If you make a request, we have one month to respond to you. If you would like to exercise any of these rights, please contact us.
    </p>

    <br>

    <h4>Contact Us</h4>
    <br>
    <p>
        Don't hesitate to contact us if you have any questions.
    </p>
    <br>
    <p>
        <a href="mailto:help@Jyro.com">help@Jyro.com</a>
    </p>
</div>
</div>			
	<!--  -->

	<!--Footer  -->
 <?php include "footer.php"; ?>
	<!-- End Footer -->

	<!-- script -->
	<script src="js/vendor.bundle.js"></script>
	<script src="js/script.js"></script>


</body></html>