
<?php include "header.php"; ?>

<body data-spy="scroll" data-target="#navbar" data-offset="70" style="overflow: visible;">

	<!-- Preloader -->
	<div id="preloader" style="display: none;">
		<div id="status" style="display: none;">&nbsp;</div>
	</div>
	<!--  -->

	<!-- header -->
	<header>
		<!-- navbar -->
		<nav id="navbar" class="navbar navbar-custom navbar-fixed-top affix-top" data-spy="affix" data-offset-top="70">
			<div class="container">
				<div class="row">
					<!-- Brand and toggle get grouped for better mobile display -->
					<div class="navbar-header page-scroll">
						<button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
							<i class="fa fa-bars"></i>
						</button>
            <a class="navbar-brand page-scroll logo-light" style="width: 135px;height: 45px;" href="/"><img alt="" src="img/svgs/MainJyroLogo.svg"></a>
						<a class="navbar-brand page-scroll logo-clr" style="width: 135px;height: 45px;" href="/"><img alt="" src="img/svgs/MainJyroLogo.svg"></a>
          </div>

					<!-- Collect the nav links, forms, and other content for toggling -->
					<div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
						<div class="right-nav text-right">
							<!-- <ul class="nav navbar-nav menu">
								<li class="active">
						 			<a href="#home">Home</a>  
								</li>
								<li>
									<a href="#feature">Feature</a>
								</li>
								<li>
									<a href="#overview">Overview</a>
								</li>
								<li>
									<a href="#How">How Work?</a>
								</li>
								<li>
									<a href="#team">Team</a>
								</li>
							</ul> -->
						</div>
					</div>
					<!-- /.navbar-collapse -->
				</div>
			</div>
		</nav>
		<!-- End navbar -->

		<!-- banner -->
		<div class="terms" style="padding-top: 150px;">
            <div class="container">
                <h3>Terms &amp; Conditions</h3>
                <p>
                Updated at 2020-08-28
                </p>
                <br>

                <h3>License</h3>
                
                <p>
                  Jyro App grants you a revocable, non-exclusive, non-transferable, limited license to download, install and use the website/app strictly in accordance with the terms of this Agreement.
                </p>
                <br>
              
                <h3>Meanings</h3>
                <p>
                  For this Privacy Policy:
                </p>
                <br>
               
                <p>
                  1. You is referred to the person who accessed the Service, or the company, or other legal entity on behalf of which such
                  individual is accessing or using the Service, as applicable.<br>
                  2. Company (referred to as either "the Company", "We", "Us" or "Our" in this Agreement) refers to Front-TSL Limited, Lagos<br>
                  3. Website is referred to Jyro.<br>
                  4. Service is referred to the website/app.<br>
                  5. Service Provider means any natural or legal person who processes the data on behalf of the Company. It refers to
                  third-party companies or individuals employed by the Company to facilitate the Service, to provide the Service on behalf of the Company, to perform services related to the Service or to assist the Company in analyzing how the Service is used.<br>
                  6. Third-party Social Media Service could be any website or social network website in which a User can log in or create an
                  account to use the Service.<br>
                  7. Personal Data is any information that relates to an identified or identifiable individual.<br>
                  8. Cookies are a small amount of data generated by a website and saved by your web browser. Its purpose is to remember information about you, similar to a preference file created by a software application.<br>
                  9. Device could be any device with internet who can access the service such as a mobile phone, a computer or a digital tablet.<br>
                  10. Usage Data it’s referred to the data that’s been collected automatically, either generated by the use of the Service or from the Service infrastructure itself. For example, how many times the user accessed the website/app.<br>
                </p>
                <br>
              

                <h3>Restrictions</h3>
                <p>
                  You agree not to, and you will not permit others to:
                </p>
                <br>

                <p>
                  1. License, sell, rent, lease, assign, distribute, transmit, host, outsource, disclose or otherwise commercially exploit the website/app or make the platform available to any third party.s<br>
                  2. Modify, make derivative works of, disassemble, decrypt, reverse compile or reverse engineer any part of the website/app.<br>
                  3. Remove, alter or obscure any proprietary notice (including any notice of copyright or trademark) of Jyro App or its affiliates, partners, suppliers or the licensors of the website/app.<br>
                </p>
                <br>

                <h3>Return and Refund Policy</h3>
                
                <p>If, for any reason, You are not completely satisfied with any good or service that we provide, don't hesitate to contact us and we will discuss any of the issues you are going through with our product.</p><p>
                <br>

                </p><h3>Your Suggestions</h3>
                
                <p>
                  Any feedback, comments, ideas, improvements or suggestions (collectively, "Suggestions") provided by you to Jyro App with respect to the website/app shall remain the sole and exclusive property of Jyro App.<br>
                  Jyro App shall be free to use, copy, modify, publish, or redistribute the Suggestions for any purpose and in any way without any credit or any compensation to you.<br>
                </p><p>

                <br>
                </p><h3>Your Consent</h3>
                
                <p>
                By using our site, registering an account, or making a purchase, you consent to this Terms &amp; Conditions.
                </p><p>

                <br>
                </p><h3>Links to Other Websites</h3>
                
                <p>
                  Our service may contain links to other websites that are not operated by Us. If You click on a third party link, You will be directed to that third party's site. We strongly advise You to review the Terms &amp; Conditions of every site You visit.<br>
                  We have no control over and assume no responsibility for the content, Terms &amp; Conditions or practices of any third party sites or services.<br>
                </p><p>


                <br>
                </p><h3>Cookies</h3>
                
                <p>
                  Jyro App uses "Cookies" to identify the areas of our website/app that you have visited. A Cookie is a small piece of data stored on your computer or mobile device by your web browser. We use Cookies to personalize the Content that you see on our website/app. Most web browsers can be set to disable the use of Cookies. However, if you disable Cookies, you may not be able to access functionality on our website/app correctly or at all. We never place Personally Identifiable Information in Cookies. By using our site, registering an account, or making a purchase, you consent to the fact that we use cookies.
                </p><p>

                <br>
                </p><h3>Changes To Our Terms &amp; Conditions</h3>
                
                <p>
                  You acknowledge and agree that Jyro may stop (permanently or temporarily) providing the Service (or any features within the Service) to you or to users generally at Jyro’s sole discretion, without prior notice to you. You may stop using the Service at any time. You do not need to specifically inform Jyro when you stop using the Service. You acknowledge and agree that if Jyro disables access to your account, you may be prevented from accessing the Service, your account details or any files or other materials which is contained in your account.<br>
                  If we decide to change our Terms $ Conditions, we will post those changes on this page, and/or update the Terms &amp; Conditions modification date below.
                </p><p>


                <br>
                </p><h3>Modifications to Our website/app</h3>
                
                <p>
                  Jyro App reserves the right to modify, suspend or discontinue, temporarily or permanently, the website/app or any service to which it connects, with or without notice and without liability to you.
                </p><p>

                <br>
                </p><h3>Updates to Our website/app</h3>
                
                <p>
                  Jyro App may from time to time provide enhancements or improvements to the features/ functionality of the website/app, which may include patches, bug fixes, updates, upgrades and other modifications ("Updates").<br>
                  Updates may modify or delete certain features and/or functionalities of the website/app. You agree that Jyro App has no obligation to (i) provide any Updates, or (ii) continue to provide or enable any particular features and/or functionalities of the website/app to you.<br>
                  You further agree that all Updates will be (i) deemed to constitute an integral part of the website/app, and (ii) subject to the terms and conditions of this Agreement.<br>
                </p><p>
                <br>

                </p><h3>Third-Party Services</h3>
                
                <p>
                  We may display, include or make available third-party content (including data, information, applications and other products services) or provide links to third-party websites or services ("Third- Party Services").<br>
                  You acknowledge and agree that Jyro App shall not be responsible for any Third-Party Services, including their accuracy, completeness, timeliness, validity, copyright compliance, legality, decency, quality or any other aspect thereof. Jyro App does not assume and shall not have any liability or responsibility to you or any other person or entity for any Third-Party Services.<br>
                  Third-Party Services and links thereto are provided solely as a convenience to you and you access and use them entirely at your own risk and subject to such third parties' terms and conditions.<br>
                </p><p>
                <br>

                </p><h3>Term and Termination</h3>
                
                <p>
                  This Agreement shall remain in effect until terminated by you or Jyro App.<br>
                  Jyro App may, in its sole discretion, at any time and for any or no reason, suspend or terminate this Agreement with or without prior notice.<br>
                  This Agreement will terminate immediately, without prior notice from Jyro App, in the event that you fail to comply with any provision of this Agreement. You may also terminate this Agreement by deleting the website/app and all copies thereof from your computer.<br>
                  Upon termination of this Agreement, you shall cease all use of the website/app and delete all copies of the website/app from your computer.<br>
                  Termination of this Agreement will not limit any of Jyro App's rights or remedies at law or in equity in case of breach by you (during the term of this Agreement) of any of your obligations under the present Agreement.<br>
                </p><p>
                <br>

                </p><h3>Indemnification</h3>
                
                <p>
                  You agree to indemnify and hold Jyro App and its parents, subsidiaries, affiliates, officers, employees, agents, partners and licensors (if any) harmless from any claim or demand, including reasonable attorneys' fees, due to or arising out of your: (a) use of the website/app; (b) violation of this Agreement or any law or regulation; or (c) violation of any right of a third party.
                </p><p>
                <br>

                </p><h3>No Warranties</h3>
                
                <p>
                  The website/app is provided to you "AS IS" and "AS AVAILABLE" and with all faults and defects without warranty of any kind. To the maximum extent permitted under applicable law, Jyro App, on its own behalf and on behalf of its affiliates and its and their respective licensors and service providers, expressly disclaims all warranties, whether express, implied, statutory or otherwise, with respect to the website/app, including all implied warranties of merchantability, fitness for a particular purpose, title and non-infringement, and warranties that may arise out of course of dealing, course of performance, usage or trade practice. Without limitation to the foregoing, Jyro App provides no warranty or undertaking, and makes no representation of any kind that the website/app will meet your requirements, achieve any intended results, be compatible or work with any other software, , systems or services, operate without interruption, meet any performance or reliability standards or be error free or that any errors or defects can or will be corrected.<br>
                  Without limiting the foregoing, neither Jyro App nor any Jyro App's provider makes any representation or warranty of any kind, express or implied: (i) as to the operation or availability of the website/app, or the information, content, and materials or products included thereon; (ii) that the website/app will be uninterrupted or error-free; (iii) as to the accuracy, reliability, or currency of any information or content provided through the website/app; or (iv) that the website/app, its servers, the content, or e-mails sent from or on behalf of Jyro App are free of viruses, scripts, trojan horses, worms, malware, timebombs or other harmful components.<br>
                  Some jurisdictions do not allow the exclusion of or limitations on implied warranties or the limitations on the applicable statutory rights of a consumer, so some or all of the above exclusions and limitations may not apply to you.<br>
                </p><p>
                <br>

                </p><h3>Limitation of Liability</h3>
                
                <p>
                  Notwithstanding any damages that you might incur, the entire liability of Jyro App and any of its suppliers under any provision of this Agreement and your exclusive remedy for all of the foregoing shall be limited to the amount actually paid by you for the website/app.<br>
                  To the maximum extent permitted by applicable law, in no event shall Jyro App or its suppliers be liable for any special, incidental, indirect, or consequential damages whatsoever (including, but not limited to, damages for loss of profits, for loss of data or other information, for business interruption, for personal injury, for loss of privacy arising out of or in any way related to the use of or inability to use the website/app, third-party software and/or third-party hardware used with the website/app, or otherwise in connection with any provision of this Agreement), even if Jyro App or any supplier has been advised of the possibility of such damages and even if the remedy fails of its essential purpose.<br>
                  Some states/jurisdictions do not allow the exclusion or limitation of incidental or consequential damages, so the above limitation or exclusion may not apply to you.<br>
                </p><p>
                <br>


                </p><h3>Severability</h3>
                
                <p>
                  If any provision of this Agreement is held to be unenforceable or invalid, such provision will be changed and interpreted to accomplish the objectives of such provision to the greatest extent possible under applicable law and the remaining provisions will continue in full force and effect.
                </p><p>
                <br>


                </p><h3>Waiver</h3>
                
                <p>
                  Except as provided herein, the failure to exercise a right or to require performance of an obligation under this Agreement shall not effect a party's ability to exercise such right or require such performance at any time thereafter nor shall be the waiver of a breach constitute waiver of any subsequent breach.
                </p><p>
                <br>



                </p><h3>Amendments to this Agreement</h3>
            
                
                <p>
              
                  Jyro App reserves the right, at its sole discretion, to modify or replace this Agreement at any time. If a revision is material we will provide at least 30 days' notice prior to any new terms taking effect. What constitutes a material change will be determined at our sole discretion.<br>
                  By continuing to access or use our website/app after any revisions become effective, you agree to be bound by the revised terms. If you do not agree to the new terms, you are no longer authorized to use Jyro App.<br>
               </p><p>
  


                </p></h3><h3>Entire Agreement</h3>
                <p>
                  The Agreement constitutes the entire agreement between you and Jyro App regarding your use of the website/app and supersedes all prior and contemporaneous written or oral agreements between you and Jyro App.<br>
                  You may be subject to additional terms and conditions that apply when you use or purchase other Jyro App's services, which Jyro App will provide to you at the time of such use or purchase.<br>
                </p>
                <br>




                <h3>Disclaimer</h3>
                <p>
                  Jyro App is not responsible for any content, code or any other imprecision.<br>
                  Jyro App does not provide warranties or guarantees.<br>
                  In no event shall Jyro App be liable for any special, direct, indirect, consequential, or incidental damages or any damages whatsoever, whether in an action of contract, negligence or other tort, arising out of or in connection with the use of the Service or the contents of the Service. The Company reserves the right to make additions, deletions, or modifications to the contents on the Service at any time without prior notice.<br>
                </p>
                <br>


                <h3>Contact Us</h3>
                <p>
                  Don't hesitate to contact us if you have any questions.<br>
                  <a href="mailto:help@jyro.com">help@jyro.com</a>
                </p>
                <br>

        </div>
	<!--  -->

	<!--Footer  -->
  <?php include "footer.php"; ?>


	<!-- script -->
	<script src="js/vendor.bundle.js"></script>
	<script src="js/script.js"></script>


</body></html>